GET http://localhost:8080

###

POST http://localhost:8080/events HTTP/1.1
content-type: application/json

{
    "id": "abc-123-xyz-789",
    "type": "TestEvent",
    "streamName": "test-stream",
    "data": {
        "key": "value"
    },
    "metadata": {
        "some": "thing"
    }
}

###

GET http://localhost:8080/events/test-stream/all

###

GET http://localhost:8080/events/test-stream/last
