GET http://localhost:8080/

###

GET http://localhost:8080/ping

###

GET http://localhost:8080/events

###

POST http://localhost:8080/events HTTP/1.1
content-type: application/json

{
    "type": "TestEvent",
    "streamName": "test-stream",
    "data": {
        "key": "value"
    },
    "metadata": {
        "some": "thing"
    }
}

###

POST http://localhost:8080/events HTTP/1.1
content-type: application/json

{
    "type": "AnotherTestEvent",
    "streamName": "another-test-stream",
    "data": {
        "key": "value"
    },
    "metadata": {
        "some": "thing"
    }
}

###

GET http://localhost:8080/events/stream/test-stream

###

GET http://localhost:8080/events/stream/test-stream/last

###

GET http://localhost:8080/events/type/TestEvent

###

GET http://localhost:8080/events/cc923a44-0ac6-4f39-bdf8-5105d9a0f7db
